### ISSUE TITLE
Compiler issue

### ISSUE THREAD

**Issue by Morgan1228** [quanghona/Tiva-Oled-Library#2]
Hi Quanghona,
There is a problem which the compiler cannot finds below head files.
Do I need to add them from somewhere？

#include "font/bitmap_db.h"
#include "font/font_include.h"

many thanks.
Morgan

**Comment by quanghona** [comment]
Hello @Morgan1228,

Sorry for my late response. The files bitmap_db.h and font_include.h was added to this repo. You can put them in the 'font' folder.
Additional, you can use [LCD Dot Factory](http://www.eran.io/the-dot-factory-an-lcd-font-and-image-generator/) as I used to generate whatever font or image (converted to mono format) you like.

Hope this help,
Quang
